server:
  port: ${SERVER_PORT:1124}

swagger:
  server-url: ${SERVER_HOST_URL_SWAGGER:http://localhost:1124}

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: adminadmin
  bucket-name: test

app:
  jwt:
    secret: myGeneratedSecretKey
    expiration-in-ms: 86400000

spring:
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 8MB
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: ${SECOND_DATABASE_URL:jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8}
    username: ${SECOND_DATABASE_USER:root}
    password: ${SECOND_DATABASE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-credit-2
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
      minimum-idle: 3
      maximum-pool-size: 20
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



logging:
  level:
    org.hibernate: DEBUG


kafka:
  bootstrap-servers: kafka-148d899c-fpt-92f3.a.aivencloud.com:14918
  properties:
    ssl:
      truststore:
        location: classpath:kafka1/client.truststore.jks
        password: 123456
      keystore:
        type: PKCS12
        location: classpath:kafka1/client.keystore.p12
        password: 123456
      key:
        password: 123456
  consumer:
    group-id: groupid
  topic: topic1